POST https://nha-cho-thu-cung.herokuapp.com/login
Content-Type: application/json

{
    "phone": "admin",
    "password": "admin"
}

# example below

###
GET https://nha-cho-thu-cung.herokuapp.com/volunteer
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjI3NTI3NDI2LCJleHAiOjE2Mjc2MTM4MjZ9.EYf4J_Q5U1Cj0ssXgWZUcLsR1FbwsfqGl0ie7o_HyA0

###
POST https://nha-cho-thu-cung.herokuapp.com/volunteer
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjI3NTI3NDI2LCJleHAiOjE2Mjc2MTM4MjZ9.EYf4J_Q5U1Cj0ssXgWZUcLsR1FbwsfqGl0ie7o_HyA0
Content-Type: application/json

{
    "name": "Tran Quang Nguyen",
    "dob": 975344400000, 
    "gender": "male",
    "phone": "0902223120", 
    "email": "tranquangnguyen2811@gmail.com", 
    "address": "Le Van Thiem, Thanh Xuan, Ha Noi",
}

###

POST http://localhost:5000/listing/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxNDk2M2E3MGYxYzFiOTdjMTg4NCIsImlhdCI6MTYyNDI2MTMyOCwiZXhwIjoxNjI0MzQ3NzI4fQ.rEGFR_zrzanYPj-iIT5BD5xn_YqiSobf5RVVPYB0CXE
Content-Type: application/json

{
    "name": "Nha ven ho",
    "description": "Rat nhieu ca nen tha ho cau",
    "address": "Vinh",
    "price": 2000,
    "capacity": 4
}